// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Producer;

#nullable disable

namespace Producer.Migrations
{
    [DbContext(typeof(OraDbContext))]
    [Migration("20240420185249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Producer.QuoteOra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Price")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRICE");

                    b.Property<string>("ProductId")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PRODUCT_ID");

                    b.HasKey("Id");

                    b.ToTable("QUOTE", "MAE_CORE");
                });
#pragma warning restore 612, 618
        }
    }
}
